# Part 1

In [43]:
import re
import numpy as np
import math

with open('input.txt') as input:
  lines = [x.strip() for x in input.readlines()]

# Fetching the numbers
numbers = []
for line in lines[:len(lines)-1]:
  nums = [int(x) for x in re.sub(r"\s+"," ",line).split(" ")]
  numbers.append(nums)
np.array(numbers)
numbers = np.array(numbers).T

# Fetching the operations
ops = [x for x in re.sub(r"\s+"," ",lines[-1]).split(" ")]
part1 = 0

# Calculating output
for index,nums in enumerate(numbers):
  if ops[index] == '+':
    part1 += sum(nums)
  elif ops[index] == '*':
    part1 += math.prod(nums)
  else:
    print("ERROR")
    break

print("Part 1 Answer:",part1)


[[123  45   6]
 [328  64  98]
 [ 51 387 215]
 [ 64  23 314]]
Part 1 Answer: 4277556


# Part 2

In [25]:
import math

with open('input.txt') as input:
  lines = [list(x.replace("\n","")) for x in input.readlines()]


numbers=lines[:len(lines)-1]
operands= [x for x in lines[len(lines)-1:][0] if x != " "]
transposed_numbers = [list(row) for row in zip(*numbers)]

temp_nums = []
operand_index = 0
part2 = 0

for nums in transposed_numbers:
  if all(x == " " for x in nums):
    if operands[operand_index] == '+':
      part2 += sum(temp_nums)
    elif operands[operand_index] == '*':
      part2 += math.prod(temp_nums)
    else:
      print("ERROR")
      break
    temp_nums = []
    operand_index += 1
  else:
    num = int("".join(nums))
    temp_nums.append(num)

# Adding last calculations...
operand = operands[-1]
if operand == '+':
  part2 += sum(temp_nums)
elif operand == '*':
  part2 += math.prod(temp_nums)
else:
  print("ERROR")


print("Part 2 Answer:",part2)

Part 2 Answer: 11494432585168
